spring.application.name=PFT
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:PFT
spring.jpa.defer-datasource-initialization=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
server.error.include-message=always

spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

secret.key=P4X2m8NqgW0HDBGnaMNCFxBXP5zFRReFgvvMHW36YovnBJQBLuBZdAagthqpC0wwrKMXP1fiDIJoZu/BPaAgcAQeXJQjK+ynKSVzU2Oztl7oVA0Xs2UrxdR7FPxPleL2eQVjHmst1tMmx+MTWTua4XPIaNl5eMM0uUz7R+AFSPQR/unuwIV8KD8xvI9AM5CrJVL0vDMDqyOxuMIQc1FYiq7VLMGO4zkJdyUp7nHZNuPxOcHGY9cVOGsgbv06gKuKMRLCjTzu18navfnzkitvU1re0gP2NINQj0YZadLEFQVuTfpnsPkaLfpPzVGDUecSW4ZtMnMSVgq07Tev0q0+Tit1mSfhOr1Hmt5A7CxsLLI=


